# -*- coding: utf-8 -*-
"""Otomatisasi Scrapping Image.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NUHpw5L2mEe-QfC1X6D0NEPolW0vom8r

OTOMATISASI SCRAPPING GAMBAR DARI WEBSITE PINTEREST
"""

pip install beautifulsoup4 requests

pip install Pillow

"""CONTOH 4 (TAMBAHAN)"""

import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin
from PIL import Image
from io import BytesIO

def scrape_image_info(url):
    # Menambahkan header untuk memanggil permintaan dari browser
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'
    }

    try:
        response = requests.get(url, headers=headers)
        response.raise_for_status()  # Mengecek apakah permintaan berhasil
    except requests.exceptions.HTTPError as errh:
        print("HTTP Error:", errh)
        return None, None
    except requests.exceptions.ConnectionError as errc:
        print("Error Connecting:", errc)
        return None, None
    except requests.exceptions.Timeout as errt:
        print("Timeout Error:", errt)
        return None, None
    except requests.exceptions.RequestException as err:
        print("Error:", err)
        return None, None

    soup = BeautifulSoup(response.text, 'html.parser')

    # Mencari tag gambar pertama dengan atribut src dan mencari judul atau deskripsi
    img_tag = soup.find('img', src=True)
    title_tag = soup.find('title')
    description_tag = soup.find('meta', attrs={'name': 'description'})

    img_url = None
    title = None
    description = None

    if img_tag:
        img_url = urljoin(url, img_tag['src'])

    if title_tag:
        title = title_tag.text.strip()

    if description_tag:
        description = description_tag.get('content').strip()

    return img_url, title, description

def display_image_info(url):
    image_url, title, description = scrape_image_info(url)

    if image_url:
        print(f"Image URL: {image_url}")
        print(f"Title: {title}")
        print(f"Description: {description}")

        response = requests.get(image_url)
        response.raise_for_status()

        # Membaca gambar dari respons
        img = Image.open(BytesIO(response.content))

        # Konversi gambar ke mode RGB
        img = img.convert("RGB")

        # Menampilkan gambar
        img.show()

if __name__ == "__main__":
    website_url = input("Masukkan URL gambar: ")

    display_image_info(website_url)



